In [1]:
import pandas as pd
import numpy as np
import statsmodels.formula.api as smf
from numpy.linalg import inv

In [24]:
# Display all cell results (not only last one)
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [3]:
dados = pd.read_csv('https://raw.githubusercontent.com/Cayan-Portela/ceub/main/dados/df_notas.csv')
dados.head()

nota  hrs_estudo  faltas
0   9.0         4.0       2
1   7.0         4.0       1
2   5.5         2.0       4
3   8.0         3.0       1
4   2.0         0.5       5

In [19]:
modelo_1 = smf.ols("nota ~ hrs_estudo", data=dados).fit()
modelo_2 = smf.ols("nota ~ hrs_estudo + faltas", data=dados).fit()

In [21]:
print(f"Intercepto: {modelo_1.params['Intercept']:.2f} | Horas de estudo: {modelo_1.params['hrs_estudo']:.2f}")

Intercepto: 2.30 | Horas de estudo: 1.50


In [32]:
v1 = np.ones(5)
v2 = np.array([1, 2, 3, 4, 5])

np.c_[v1, v2]
np.column_stack((v1, v2))


array([[1., 1.],
       [1., 2.],
       [1., 3.],
       [1., 4.],
       [1., 5.]])

array([[1., 1.],
       [1., 2.],
       [1., 3.],
       [1., 4.],
       [1., 5.]])

In [10]:
colunas = ['hrs_estudo', 'faltas']
n_ = dados.shape[0]
col_1 = np.ones(n_)
col_var = dados[colunas]
X_mat = np.c_[col_1, np.array(col_var)]

Intercept     3.502605
hrs_estudo    1.266010
faltas       -0.260563
dtype: float64

In [14]:
X_mat = matriz_x(colunas = ['hrs_estudo', 'faltas'], dados=dados)

In [17]:
inv(X_mat.T @ X_mat)

array([[ 4.95765441, -1.01477833, -0.98285335],
       [-1.01477833,  0.2364532 ,  0.18719212],
       [-0.98285335,  0.18719212,  0.21229632]])

In [33]:
modelo_2.params

Intercept     3.502605
hrs_estudo    1.266010
faltas       -0.260563
dtype: float64

In [34]:
modelo_res = smf.ols("hrs_estudo ~ faltas", data=dados).fit()

In [37]:
modelo_3 = smf.ols("nota ~ estudo_residuo", data=dados.assign(estudo_residuo=modelo_res.resid)).fit()
modelo_3.params

Intercept         5.40000
estudo_residuo    1.26601
dtype: float64

In [11]:
def matriz_x(colunas, dados):
    """Cria matriz de delineamento

    colunas: lista com nomes das colunas.
    dados: data.frame utilizado.
    """
    n_ = dados.shape[0]
    col_1 = np.ones(n_)
    col_var = dados[colunas]

    X_mat = np.c_[col_1, np.array(col_var)]

    return X_mat